### ISSUE TITLE
V2.0 Design preparation - LO-FI & USER FLOW

### ISSUE THREAD

**Issue by mylesieong** [mylesieong/Seated-Exercises-in-Vehicles#158]

**Comment by Maviskao** [comment]
Documentation [MIRO](https://miro.com/welcomeonboard/UDRLQWJxVG9RU3FTMUdQMlJidHdzWmp3dG1BVEJZa0tmZDcyVzgzcTdFMjJobERZSWw4c2t1MzgwQkE3Vml2V3wzMDc0NDU3MzU5MTQ0OTg2MzE5fDI=?share_link_id=312622009170):

LO-FI Wirefreme v1.0 - Completed (2023/02/24)
- Draft

LO-FI Wirefreme v1.1 - Completed (2023/03/01) 
### **HOME**
Functions revised below:
- Avatar: Remove
- Greeting: Separating into 2 types of interaction
   (1) It shows up on the "greetings" and "progress bar" when users set the schedule.
   (2) Showing "greetings" only when users closed the schedule.
- Add an action button for the set schedule when users haven't opened it.
- Challenge: Keep it.
- Calendar: New

### **TRAINING**
- Motto: Remove
- 
- ### **MINE**
- Daily record: Keep it.
- Accumulation record: Keep it.
- Schedule: New
- Reminder: Keep it.
- About us: New
- Feedback(Proxy):  New

User flow v1.0 - Completed (2023/03/01) 
Documentation [MIRO](https://miro.com/welcomeonboard/UDRLQWJxVG9RU3FTMUdQMlJidHdzWmp3dG1BVEJZa0tmZDcyVzgzcTdFMjJobERZSWw4c2t1MzgwQkE3Vml2V3wzMDc0NDU3MzU5MTQ0OTg2MzE5fDI=?share_link_id=312622009170):
