### ISSUE TITLE
Run focus group meeting to validate our product assumption

### ISSUE THREAD

**Issue by mylesieong** [mylesieong/Seated-Exercises-in-Vehicles#184]

**Comment by Maviskao** [comment]
**### Focus group proceed**

**Introduction:** 
Welcome the participants and explain the purpose of the focus group, which is to gather feedback on a new app designed to help people stay active and healthy during their daily routines.

**Warm-up questions**
1. 你多久運動一次？
1. How often do you exercise?
2. 你通常會做什麼運動呢？
2. What kinds of activities do you enjoy?
3. 你覺得每天運動10分鐘對是一種挑戰嗎？
3. Do you find it challenging to stay active during a typical day?

**Concept testing questions:**
(Experience in Office/fixed space )
1. 在辦公室/固定場所工作的經驗中，您大約多久會離開位子休息一次呢?
1. In the experience of working in an office, how often do you leave your seat for a break?

2. 您有在辦公室/固定場所伸展身體或是做核心運動嗎？如果有一次的運動大概會花多少時間？
2. How do you think about stretching/core exercise in the office? How many minutes do you spend at one time?

3. 您有在辦公室裡用過輔助工具(例如健身器材)幫助您運動嗎？如果有會是什麼？
3. Have you ever used an assistive device (such as exercise equipment) in the office to help you exercise? If so, what would they be?

**(Experience in transportation )**
1. 您在長途旅行或飛行過程中是否有過疼痛或不適感? 當時您如何解決？
1. Have you ever experienced any pain or discomfort during a long ride or flight? How did you solve it?

2. 您認為在辦公室或是交通工具運動時，會感覺到不自在嗎？如果有請敘述您的感受。
2. Do you feel uncomfortable while exercising in the office or on transportation? If so, please tell us how you feel.

3. 您是否嘗試過應用程序或方法在長途旅行中進行鍛煉? 請分享應用程序的名字及優點
3. Have you tried any other apps or methods for exercising during long trips? Please share the app and advantage with us.

**User experience questions**
1. 你對車輛中的坐姿鍛煉應用的初步想法是什麼?
1. What are your initial thoughts about Seated Exercise in Vehicles app?

2. 請操作這個fitness的App的伸展運動的部分,進行1~2次的伸展運動練習,跟我們分享您的想法
2. Please operate the stretching part of this fitness App, perform 1 or 2 stretching exercises, and share your thoughts with us

3. 你對應用程序中提供的各種練習有什麼看法? 你認為該應用程序的動畫和插圖對演示練習有幫助嗎?
3. What do you think about the variety of exercises offered in the app? Do you think the app's animations and illustrations are helpful in demonstrating the exercises?

你在使用該應用程序時是否有任何不適或疼痛?
Have you experienced any discomfort or pain while using the app?


4. 你對該應用程序的設計和用戶界面有何看法?
4. What do you think of the app's design and user interface?
(Share the new design of v2.0 )



**Feedback and suggestions:**
1. 你希望在該應用中增加哪些額外的功能?
1. What additional features would you like to see added to the app?

2. 你向朋友或家人推薦這個應用程序的可能性有多大?
2. How likely would you be to recommend this app to a friend or family member?

3. 你認為該應用程序的免責聲明是否清楚和充分?
3. Do you think the app's disclaimer is clear and sufficient?

4. 你今後繼續使用該應用程序的可能性有多大?
4. How likely are you to continue using the app in the future?

5. 你是否願意為該應用程序的額外功能付費?
5. Are you willing to pay for additional features of the application?



**Wrap-up:**
Thank the participants for their feedback and ask if they have any final thoughts or comments.
