### ISSUE TITLE
[#121] On Android platform, the header is too big

### ISSUE THREAD

**Issue by mylesieong** [mylesieong/Seated-Exercises-in-Vehicles#232]

**Comment by akaka0039** [comment]
![Image](https://user-images.githubusercontent.com/40246308/224872745-ccedb66f-7d5f-4031-b156-72a2a253062a.png)

**Comment by j3rryzh** [comment]
This happens only on home page or on every pages?

**Comment by akaka0039** [comment]
every pages happened

**Comment by akaka0039** [comment]
still too big on my phone(Pixel_4_API_30)
