### ISSUE TITLE
[#238] [History] The arrow on the calendar to move to another month should be visible for ios

### ISSUE THREAD

**Issue by akaka0039** [mylesieong/Seated-Exercises-in-Vehicles#307]

**Comment by j3rryzh** [comment]
Duplicate with [UI] The arrows of the history page calendar disappear when using dark mode #260 
We can't see this bug in expo preview while developing but it shows after building the app.

**Comment by akaka0039** [comment]
![image](https://user-images.githubusercontent.com/40246308/226431996-36ff4d8b-8a36-4f96-9a33-b3a2272b0e10.jpeg)

**Comment by j3rryzh** [comment]
Is this happen in local expo preview?

**Comment by akaka0039** [comment]
no. I can see the arrow now on the calendar in history page in expo preview.

**Comment by akaka0039** [comment]
This is okay. I can see arrow on both side in building one
